version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: redis
  web:
    image: unmanbearpig/jobomon-rails-app
    command: ls /rails.pid
    command: bundle exec rails s -p 3000 -b '0.0.0.0' --pid /rails.pid
    env_file: rails_app/.env.production
    ports:
      - "3010:3000"
    depends_on:
      - postgres
      - redis
  worker:
    image: unmanbearpig/jobomon-rails-app
    command: bundle exec sidekiq
    env_file: rails_app/.env.production
    depends_on:
      - postgres
      - redis
volumes:
  dbdata:
